# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZpwQhuafl8hZWybluo3waEw5sTxWQPyA
"""

!pip install -q diffusers transformers accelerate

import torch
from diffusers import StableDiffusionPipeline
import matplotlib.pyplot as plt

def generate_image_open_source(prompt_text, output_filename="diffusion_output.png"):
    """
    Loads a completely open-access stable diffusion version onto the cloud T4 GPU.
    This routes around the Hugging Face credential gates and works directly with PyTorch.
    """
    # Using an alternative, completely open checkpoint to bypass the OS access restrictions
    model_id = "CompVis/stable-diffusion-v1-4"

    print("=" * 70)
    print(f"1. Loading open-access PyTorch weights: {model_id}")
    print("Downloading structural model parameters onto the cloud server...")
    print("=" * 70)

    try:
        # Load the model using float16 half-precision for fast execution on the T4 GPU
        pipe = StableDiffusionPipeline.from_pretrained(
            model_id,
            torch_dtype=torch.float16
        )

        # Ship the pipeline execution directly to the free cloud GPU engine
        pipe = pipe.to("cuda")

        print("\n2. Engine initialized successfully on GPU!")
        print(f"Processing text prompt: '{prompt_text}'")
        print("Running reverse diffusion denoising loops... Please wait...")
        print("-" * 70)

        # Disable tracking gradients to preserve system memory space
        with torch.inference_mode():
            # num_inference_steps=25 creates crisp structures efficiently
            result = pipe(
                prompt_text,
                guidance_scale=7.5,
                num_inference_steps=25
            )
            image = result.images[0]

        # Save the final image file locally to the Colab instance disk
        image.save(output_filename)
        print(f"\n3. Success! Visual asset file generated and saved as '{output_filename}'\n")

        # Display the rendered image canvas inside your browser window area
        plt.figure(figsize=(7, 7))
        plt.imshow(image)
        plt.axis("off")
        plt.show()
        print("=" * 70)

    except Exception as e:
        print(f"\nAn error occurred during runtime: {str(e)}")
        print("\nIf you see a network timeout, try running the cell one more time.")

# =====================================================================
# INTERNSHIP SUBMISSION TASK RUNNER
# =====================================================================
if __name__ == "__main__":
    my_creative_prompt = "A majestic fantasy castle perched on top of a glowing crystal mountain, digital concept art style, highly detailed"

    generate_image_open_source(prompt_text=my_creative_prompt)

import tensorflow as tf
import tensorflow_hub as hub
import matplotlib.pyplot as plt
import numpy as np

def create_synthetic_images():
    """
    Creates clean, self-contained images locally inside Colab memory
    to completely bypass 403 Forbidden web download errors.
    """
    # Create a structured geometric content image (similar to architecture)
    content = np.zeros((384, 512, 3), dtype=np.float32)
    for i in range(16, 384, 32):
        content[i:i+8, 50:462, :] = [0.2, 0.4, 0.8]  # Blue structures
    for j in range(64, 462, 48):
        content[100:300, j:j+12, :] = [0.7, 0.5, 0.3]  # Pillars

    # Create an artistic abstract style canvas with color patterns
    style = np.zeros((384, 512, 3), dtype=np.float32)
    x, y = np.meshgrid(np.linspace(-2, 2, 512), np.linspace(-2, 2, 384))
    r = np.sqrt(x**2 + y**2)
    style[:, :, 0] = np.abs(np.sin(r * 5))  # Vivid red waves
    style[:, :, 1] = np.abs(np.cos(x * 3))  # Vivid green textures
    style[:, :, 2] = np.abs(np.sin(y * 4))  # Vivid blue swirls

    # Expand dims to match standard neural network batch requirements
    content_tensor = tf.convert_to_tensor(content)[tf.newaxis, ...]
    style_tensor = tf.convert_to_tensor(style)[tf.newaxis, ...]
    return content_tensor, style_tensor

def tensor_to_image(tensor):
    """Converts a processing tensor back into a viewable image array."""
    tensor = tensor * 255
    tensor = np.array(tensor, dtype=np.uint8)
    if np.ndim(tensor) > 3:
        assert tensor.shape[0] == 1
        tensor = tensor[0]
    return tensor

def run_local_style_transfer(output_filename="PRODIGY_GA_05.png"):
    print("=" * 70)
    print("1. Generating secure local content and style canvases...")
    print("=" * 70)

    try:
        content_image, style_image = create_synthetic_images()

        print("\n2. Loading pre-trained VGG Style Transfer Network from TF-Hub...")
        print("This handles loss optimization dynamically in a single forward pass...")
        print("-" * 70)

        # Load the stable Magenta fast style transfer model architecture
        hub_model = hub.load('https://tfhub.dev/google/magenta/arbitrary-image-stylization-v1-256/2')

        print("Blending content structure with style textures...")
        stylized_image_tensor = hub_model(content_image, style_image)[0]

        # Convert outputs back to pixel formats
        final_image = tensor_to_image(stylized_image_tensor)

        # Save the result image file locally to your notebook workspace
        plt.imsave(output_filename, final_image)
        print(f"\n3. Success! Artistic image saved to your directory as '{output_filename}'\n")

        # Plot and display the content, style, and generated output side-by-side
        fig, axes = plt.subplots(1, 3, figsize=(15, 5))
        axes[0].imshow(tensor_to_image(content_image))
        axes[0].set_title("Original Layout Structure")
        axes[0].axis("off")

        axes[1].imshow(tensor_to_image(style_image))
        axes[1].set_title("Artistic Style Source")
        axes[1].axis("off")

        axes[2].imshow(final_image)
        axes[2].set_title("Final Stylized Output")
        axes[2].axis("off")

        plt.tight_layout()
        plt.show()
        print("=" * 70)

    except Exception as e:
        print(f"\nAn error occurred during runtime: {str(e)}")

if __name__ == "__main__":
    run_local_style_transfer()