# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZpwQhuafl8hZWybluo3waEw5sTxWQPyA
"""

!pip install -q diffusers transformers accelerate

import torch
from diffusers import StableDiffusionPipeline
import matplotlib.pyplot as plt

def generate_image_open_source(prompt_text, output_filename="diffusion_output.png"):
    """
    Loads a completely open-access stable diffusion version onto the cloud T4 GPU.
    This routes around the Hugging Face credential gates and works directly with PyTorch.
    """
    # Using an alternative, completely open checkpoint to bypass the OS access restrictions
    model_id = "CompVis/stable-diffusion-v1-4"

    print("=" * 70)
    print(f"1. Loading open-access PyTorch weights: {model_id}")
    print("Downloading structural model parameters onto the cloud server...")
    print("=" * 70)

    try:
        # Load the model using float16 half-precision for fast execution on the T4 GPU
        pipe = StableDiffusionPipeline.from_pretrained(
            model_id,
            torch_dtype=torch.float16
        )

        # Ship the pipeline execution directly to the free cloud GPU engine
        pipe = pipe.to("cuda")

        print("\n2. Engine initialized successfully on GPU!")
        print(f"Processing text prompt: '{prompt_text}'")
        print("Running reverse diffusion denoising loops... Please wait...")
        print("-" * 70)

        # Disable tracking gradients to preserve system memory space
        with torch.inference_mode():
            # num_inference_steps=25 creates crisp structures efficiently
            result = pipe(
                prompt_text,
                guidance_scale=7.5,
                num_inference_steps=25
            )
            image = result.images[0]

        # Save the final image file locally to the Colab instance disk
        image.save(output_filename)
        print(f"\n3. Success! Visual asset file generated and saved as '{output_filename}'\n")

        # Display the rendered image canvas inside your browser window area
        plt.figure(figsize=(7, 7))
        plt.imshow(image)
        plt.axis("off")
        plt.show()
        print("=" * 70)

    except Exception as e:
        print(f"\nAn error occurred during runtime: {str(e)}")
        print("\nIf you see a network timeout, try running the cell one more time.")

# =====================================================================
# INTERNSHIP SUBMISSION TASK RUNNER
# =====================================================================
if __name__ == "__main__":
    my_creative_prompt = "A majestic fantasy castle perched on top of a glowing crystal mountain, digital concept art style, highly detailed"

    generate_image_open_source(prompt_text=my_creative_prompt)